set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
        Plugin 'VundleVim/Vundle.vim'
        Plugin 'altercation/vim-colors-solarized'
        Plugin 'Valloric/YouCompleteMe'
        Plugin 'ternjs/tern_for_vim'
        Plugin 'tpope/vim-fugitive'
        Plugin 'vim-airline/vim-airline'
        Plugin 'vim-airline/vim-airline-themes'
        Plugin 'xuhdev/vim-latex-live-preview'
        Plugin 'maksimr/vim-jsbeautify'
        Plugin 'julialang/julia-vim'
call vundle#end()            " required

filetype plugin indent on    " required

syntax enable
colorscheme solarized

set encoding=utf-8

" settings to enable project specific .vimrc files
set exrc
set secure

set expandtab                " covert tabs to spaces
set nosmarttab
set textwidth=79
set tabstop=4
set shiftwidth=4
set softtabstop=4

if system('uname -s') == "Darwin\n"
"   only tested with sierra
    let g:livepreview_previewer='open -a preview'
else
    set clipboard=unnamedplus

    " default pdf viewer for gnome sys
    let g:livepreview_previewer='evince'

    " x clipboard workaround vim.wikia.com/wiki/Accessing_the_system_clipboard
    " dependency is xsel
    command -range Cz :silent :<line1>,<line2>w !xsel -i -b
    command -range Cx :silent :<line1>,<line2>w !xsel -i -p
    command -range Cv :silent :<line1>,<line2>w !xsel -i -s
    cabbrev cv Cv
    cabbrev cz Cz
    cabbrev cx Cx

    command -range Pz :silent :r !xsel -o -b
    command -range Px :silent :r !xsel -o -p
    command -range Pv :silent :r !xsel -o -s
    cabbrev pz Pz
    cabbrev px Px
    cabbrev pv Pv
endif

set background=dark
set number

set noswapfile
set nobackup
set nowb
set nowrap

set ignorecase
set smartcase

" youcompleteme settings
" c family
let g:ycm_global_ycm_extra_conf="~/.vim/bundle/YouCompleteMe/.ycm_extra_conf.py"

" hard coded python path, needs editing
let g:ycm_python_binary_path="/usr/bin/python3"

" airline related settings, patch the fonts after first installation
set noshowmode
set laststatus=2
set ttimeoutlen=10
let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_symbols.crypt = ''
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.spell = 'S'
let g:airline_symbols.notexists = '∄'
let g:airline_symbols.whitespace = 'Ξ'

" powerline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

" preview latex
map <F12> :LLPStartPreview<cr>

" format javascript
map <F11> :call JsBeautify()<cr>

" key bindings for autoformat c family languages
map <C-K> :pyf /usr/share/clang/clang-format.py<cr>
imap <C-K> <c-o> :pyf /usr/share/clang/clang-format.py<cr>


